language: python
python:
  - "2.7"
  - "3.6"

script:
     # install the package and test
     -./scripts/use_repo
     - pip install -e .[tests]
     - ./scripts/build_exploration
     - py.test --pep8 -m pep8 -n8
     - py.test -n8
     - ./scripts/test_pylint