algorithm: 'frontier'
footprint:
  type: 'tricky_circle'
  angular_resolution: 0.01745
  inflation_scale: 1.3

mode: 'closest-middle'
min_frontier_size: 10
max_replans: 3
planning_resolution: 0.1
planning_epsilon: 1.0
planning_delta_scale: 1.5
